#!/usr/bin/python3
import sys
from burr.cli.__main__ import cli_build_ui
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(cli_build_ui())
